=== phamthuonghai/greta-monologue/BehaviorRealizer/AnimationLexicon/HeadGestures.dtd
<!ELEMENT HeadGestures (HeadGesture)*>
<!ELEMENT HeadGesture (HeadPitch, HeadYaw)>
<!ATTLIST HeadGesture id CDATA "id" min CDATA "1" max CDATA "2" trajectory CDATA "linear">
<!ELEMENT HeadPitch (#PCDATA)>
<!ELEMENT HeadYaw (#PCDATA)>

=== phamthuonghai/greta-monologue/BehaviorRealizer/AnimationLexicon/HeadGestures.xml
<?xml version="1.0"?>
<!DOCTYPE HeadGestures SYSTEM "HeadGestures.dtd" []>
<HeadGestures> 
    <HeadGesture id="nod" min="1" max="3" trajectory="linear" >
        <HeadPitch>26.7</HeadPitch> 
        <HeadYaw>0</HeadYaw> 
	</HeadGesture>			

    <HeadGesture id="up" min="1" max="3" trajectory="linear" >
        <HeadPitch>-24.3</HeadPitch> 
        <HeadYaw>0</HeadYaw> 
	</HeadGesture>			

    <HeadGesture id="head_down" min="1" max="3" trajectory="linear" >
        <HeadPitch>25.5</HeadPitch> 
        <HeadYaw>0</HeadYaw> 
	</HeadGesture>	
	
    <HeadGesture id="down" min="1" max="3" trajectory="linear" >
        <HeadPitch>25.5</HeadPitch> 
        <HeadYaw>0</HeadYaw> 
	</HeadGesture>			
	
	<HeadGesture id="head_down_high" min="1" max="3" trajectory="linear" >
        <HeadPitch>20</HeadPitch> 
        <HeadYaw>0</HeadYaw> 
	</HeadGesture>		

	<HeadGesture id="head_down_low" min="1" max="3" trajectory="linear" >
        <HeadPitch>10</HeadPitch> 
        <HeadYaw>0</HeadYaw> 
	</HeadGesture>		

    <HeadGesture id="small_right" min="1" max="3" trajectory="linear" >
        <HeadPitch>0</HeadPitch> 
        <HeadYaw>-20</HeadYaw> 
	</HeadGesture>		
	
    <HeadGesture id="right" min="1" max="3" trajectory="linear" >
        <HeadPitch>0</HeadPitch> 
        <HeadYaw>-40</HeadYaw> 
	</HeadGesture>			

    <HeadGesture id="small_left" min="1" max="3" trajectory="linear" >
        <HeadPitch>0</HeadPitch> 
        <HeadYaw>20</HeadYaw> 
	</HeadGesture>			
	
    <HeadGesture id="left" min="1" max="3" trajectory="linear" >
        <HeadPitch>0</HeadPitch> 
        <HeadYaw>40</HeadYaw> 
	</HeadGesture>			

    <HeadGesture id="head_up_left" min="1" max="3" trajectory="linear" >
        <HeadPitch>-20</HeadPitch> 
        <HeadYaw>40</HeadYaw> 
	</HeadGesture>
	
    <HeadGesture id="up_left" min="1" max="3" trajectory="linear" >
        <HeadPitch>-20</HeadPitch> 
        <HeadYaw>40</HeadYaw> 
	</HeadGesture>			
	
    <HeadGesture id="head_up_right" min="1" max="3" trajectory="linear" >
        <HeadPitch>-20</HeadPitch> 
        <HeadYaw>-40</HeadYaw> 
	</HeadGesture>	
	
    <HeadGesture id="up_right" min="1" max="3" trajectory="linear" >
        <HeadPitch>-20</HeadPitch> 
        <HeadYaw>-40</HeadYaw> 
	</HeadGesture>			

    <HeadGesture id="head_down_left" min="1" max="3" trajectory="linear" >
        <HeadPitch>20</HeadPitch> 
        <HeadYaw>40</HeadYaw> 
	</HeadGesture>	
	
    <HeadGesture id="down_left" min="1" max="3" trajectory="linear" >
        <HeadPitch>20</HeadPitch> 
        <HeadYaw>40</HeadYaw> 
	</HeadGesture>			

	<HeadGesture id="head_down_right" min="1" max="3" trajectory="linear" >
        <HeadPitch>20</HeadPitch> 
        <HeadYaw>-40</HeadYaw> 
	</HeadGesture>	
	
    <HeadGesture id="down_right" min="1" max="3" trajectory="linear" >
        <HeadPitch>20</HeadPitch> 
        <HeadYaw>-40</HeadYaw> 
	</HeadGesture>			
	
    <HeadGesture id="down_aside_right" min="1" max="3" trajectory="linear" >
        <HeadPitch>20</HeadPitch> 
        <HeadYaw>-40</HeadYaw> 
	</HeadGesture>			
	
    <HeadGesture id="head_down_aside_r" min="1" max="3" trajectory="linear" >
        <HeadPitch>20</HeadPitch> 
        <HeadYaw>-40</HeadYaw> 
	</HeadGesture>
	
    <HeadGesture id="down_aside_lelf" min="1" max="3" trajectory="linear" >
        <HeadPitch>20</HeadPitch> 
        <HeadYaw>40</HeadYaw> 
	</HeadGesture>			
	
    <HeadGesture id="head_down_aside_l" min="1" max="3" trajectory="linear" >
        <HeadPitch>20</HeadPitch> 
        <HeadYaw>40</HeadYaw> 
	</HeadGesture>		

    <HeadGesture id="head_none" min="1" max="3" trajectory="linear" >
        <HeadPitch>0</HeadPitch> 
        <HeadYaw>0</HeadYaw> 
	</HeadGesture>		
	
    <HeadGesture id="look_at" min="1" max="3" trajectory="linear" >
        <HeadPitch>0</HeadPitch> 
        <HeadYaw>0</HeadYaw> 
	</HeadGesture>		
	
    <HeadGesture id="shake" min="1" max="3" trajectory="linear" >
        <HeadPitch>0</HeadPitch> 
        <HeadYaw>20</HeadYaw> 	
	</HeadGesture>				
</HeadGestures>
